name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances (si requirements.txt existe)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécuter le script Python
        run: python main.py
